# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2.1
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.9.4
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSword: postgres
          POSTGRES_DB: phoenix_example_test
      - image: "mariadb:10.4.11"
        environment:
          MYSQL_DATABASE: "test_db"
          MYSQL_USER: "root"
          MYSQL_ROOT_PASSWORD: "zan3Kie1"

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: docker run -p 6379:6379 -d redis:5.0.7 redis-server --requirepass TaeT9ahc --port 6379
      - run: docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -d elasticsearch:7.5.0
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
      - run: sudo apt-get update && sudo apt-get install -y apt-transport-https apt-utils curl
      - run: curl -sL https://deb.nodesource.com/setup_13.x -o nodesource_setup.sh
      - run: sudo bash nodesource_setup.sh
      - run: sudo apt install -y nodejs
      - run: curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - run: sudo apt-get update && sudo apt-get install yarn
      - run: cd assets && yarn install && node node_modules/webpack/bin/webpack.js --mode development && cd ..
      - run: MIX_ENV=prod mix compile
      - run: MIX_ENV=prod mix phx.digest
      - run: MIX_ENV=prod mix distillery.init
      - run: MIX_ENV=prod mix distillery.release
