# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2.1
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.10.3
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSword: postgres
          POSTGRES_DB: phoenix_example_test
      - image: mariadb:10.4.11
        environment:
          MYSQL_DATABASE: "test_db"
          MYSQL_USER: "root"
          MYSQL_ROOT_PASSWORD: "zan3Kie1"
      - image: rabbitmq:3.8.3-management-alpine
        environment:
          RABBITMQ_DEFAULT_USER: "user"
          RABBITMQ_DEFAULT_PASS: "Anaith7x"
          RABBITMQ_ERLANG_COOKIE: "Chiew0irtoh9Peeg"
          RABBITMQ_DEFAULT_VHOST: "vhost_name"
      - image: elasticsearch:7.8.0
        environment:
         discovery.type: single-node
      - image: mongo:4.2-bionic
        environment:
          MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
          MONGO_INITDB_ROOT_PASSWORD: "Iushahb0"
          MONGO_INITDB_DATABASE: "notadmin"
          MONGO_NON_ROOT_USERNAME: "normal"
          MONGO_NON_ROOT_PASSWORD: "Iushahb0"

    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout

      # specify any bash command here prefixed with `run: `
      # - run: docker run -p 5672:5672 -p 15672:15672 -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=Anaith7x -e RABBITMQ_DEFAULT_VHOST="/" -e RABBITMQ_ERLANG_COOKIE='Chiew0irtoh9Peeg' -d rabbitmq:3.8.2-management-alpine
      - run: docker run -p 6379:6379 -d redis:5.0.7 redis-server --requirepass TaeT9ahc --port 6379
      ## see https://discuss.circleci.com/t/cannot-connect-to-rabbitmq/19830 , the rabbitmq need some times to start
      - run: sleep 10
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run:
          command: mix compile
          no_output_timeout: 120m
      - run:
          command: mix ecto.create
          no_output_timeout: 120m
      - run: mix test
      - run: sudo apt-get update && sudo apt-get install -y apt-transport-https apt-utils curl
      - run: curl -sL https://deb.nodesource.com/setup_13.x -o nodesource_setup.sh
      - run: sudo bash nodesource_setup.sh
      - run: sudo apt install -y nodejs
      - run: curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - run: sudo apt-get update && sudo apt-get install yarn
      - run: cd assets && yarn install && node node_modules/webpack/bin/webpack.js --mode development && cd ..
      - run:
          command: MIX_ENV=prod mix compile
          no_output_timeout: 120m
      - run: MIX_ENV=prod mix phx.digest
      - run: MIX_ENV=prod mix distillery.init
      - run: MIX_ENV=prod mix distillery.release
      - run:
          command: mix credo
          no_output_timeout: 120m
      - run: curl -X GET "localhost:9200/_cat/nodes?v&pretty"
