name: elixir_ci

on: push

jobs:
  build:

    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:12.1
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --privileged
          --restart always
        env:
          TIMEZONE: Asia/Shanghai
          POSTGRES_DB: phoenix_example_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
#      mariadb:
#        image: mariadb:10.4.10
#        ports:
#          - 3306:3306
#        options: >-
#          --privileged
#          --restart always
#          --health-cmd "mysqladmin -pzan3Kie1 -P3800 ping"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 3
##          --entrypoint docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#        env:
#          TIMEZONE: Asia/Shanghai
#          MYSQL_DATABASE: test_db
#          MYSQL_ROOT_PASSWORD: zan3Kie1
      redis:
        image: redis
        ports:
          - 6379:6379

##    container:
##      image: elixir:1.9.4-slim
##      env:
##        POSTGRES_HOSTNAME: postgres
##        POSTGRES_DB: phoenix_example_test
##        POSTGRES_USER: postgres
##        POSTGRES_PASSWORD: postgres
##        POSTGRES_PORT: 5432
##        MARIADB_HOSTNAME: mariadb
##        MARIADB_DB: test_db
##        MARIADB_USER: root
##        MARIADB_PASSWORD: zan3Kie1
##        MARIADB_PORT: 3800

    steps:
    - uses: actions/checkout@v1
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - uses: getong/mariadb-action@v1
      with:
        host port: 3800
        container port: 3306
        mysql version: 10.4.10
        mysql database: test_db
        mysql root password: zan3Kie1
    - name: Install Dependencies
      run: |
        wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
        sudo dpkg -i erlang-solutions_1.0_all.deb
        sudo apt-get update
        sudo apt-get install -y erlang wget unzip
        wget -c https://github.com/elixir-lang/elixir/releases/download/v1.9.4/Precompiled.zip
        mkdir elixir
        unzip Precompiled.zip -d elixir
        export PATH=./elixir/bin/:$PATH
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: |
        export PATH=./elixir/bin/:$PATH
        MIX_ENV=test mix compile
        mix test
        MIX_ENV=prod mix compile
        MIX_ENV=prod mix distillery.init
        MIX_ENV=prod mix distillery.release
        ./_build/prod/rel/phoenix_example/bin/phoenix_example foreground
        # ./_build/prod/rel/phoenix_example/bin/phoenix_example ping
        ./_build/prod/rel/phoenix_example/bin/phoenix_example stop
